CREATE TABLE IF NOT EXISTS room (
  id SERIAL PRIMARY KEY,
  capacity INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL,
  description TEXT,
  maintenance_reason VARCHAR(50) NULL,
  is_available BOOLEAN NULL
);


CREATE TABLE IF NOT EXISTS session (
  id SERIAL PRIMARY KEY,
  room_id INT NOT NULL,
  user_id INT NOT NULL,
  date TIMESTAMP NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  confirmed BOOLEAN NULL,
  CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_users_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

